version: '3.1'

services:
  wordpress:
    depends_on:
      - db
    image: testelkapl/test-bookstore-wordpress:2.0
    restart: always
    ports:
      - 8889:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WP_HOME: http://localhost:8889
      WP_SITEURL: http://localhost:8889
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wpsite

  db:
    image: testelkapl/test-bookstore-mysql:2.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    cap_add:
      - SYS_NICE
    networks:
      - wpsite

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
    networks:
      - wpsite

networks:
  wpsite:

volumes:
  db_data: {}
  wordpress_data: {}
